/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cylin' at '12/2/16 10:21 PM' with Gradle 3.2.1
 *
 * @author cylin, @date 12/2/16 10:21 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
